version: '3.8'
services:
  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "4000:4000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: task-frontendgit
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
